// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from networks.djinni

#ifndef DJINNI_GENERATED_NJSNETWORKS_HPP
#define DJINNI_GENERATED_NJSNETWORKS_HPP


#include "../../../core/src/api/BitcoinLikeNetworkParameters.hpp"
#include "../../../core/src/api/CosmosLikeNetworkParameters.hpp"
#include "../../../core/src/api/EthereumLikeNetworkParameters.hpp"
#include "../../../core/src/api/RippleLikeNetworkParameters.hpp"
#include "../../../core/src/api/TezosLikeNetworkParameters.hpp"
#include <memory>
#include <string>

#include <nan.h>
#include <node.h>
#include "../../../core/src/api/Networks.hpp"

using namespace v8;
using namespace node;
using namespace std;
using namespace ledger::core::api;

class NJSNetworks final {
public:

    static void Initialize(Local<Object> target);
    NJSNetworks() = delete;

    static Local<Object> wrap(const std::shared_ptr<ledger::core::api::Networks> &object);
    static Nan::Persistent<ObjectTemplate> Networks_prototype;

private:
    /** The Bitcoin network parameters. */
    static NAN_METHOD(bitcoin);

    /** The Cosmos network parameters. */
    static NAN_METHOD(cosmos);

    /** The Ethereum network parameters. */
    static NAN_METHOD(ethereum);

    /** The Ripple network parameters. */
    static NAN_METHOD(ripple);

    /** The Tezos network parameters. */
    static NAN_METHOD(tezos);

    static NAN_METHOD(New);

    static NAN_METHOD(isNull);
};
#endif //DJINNI_GENERATED_NJSNETWORKS_HPP
