name: macOS

on:
# At the moment, only trigger on working branch
# Later, trigger on pull request
  push:
    branches:
      - github-actions-migration

env:
    source_path: 'libcore_source'
    build_path: 'libcore_build'
    open_ssl_path: '/usr/local/opt/openssl@1.1/'
    build_jar_path: 'jar_build'

jobs:

  prepare:
      runs-on: [self-hosted, macos, x64]
      steps:
        -
          name: Check runner environment
          run: |
            cmake --version
            make --version
            ctest --version
            lcov --version
            genhtml --version
            openssl version
            if [ ! -d "${{env.open_ssl_path}}" ]
            then 
              exit 1
            fi
            sbt --version
            java -version

  ###########
  # RELEASE #
  ###########
  release:
    needs: prepare
    runs-on: [self-hosted, macos, x64]
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{env.source_path}}
          clean: true
          submodules: true
      -
        name: Build - Cmake
        run: |
          if [ -d "${{env.build_path}}" ]; 
            then rm -Rf ${{env.build_path}}; 
          fi
          mkdir ${{env.build_path}}
          cd ${{env.build_path}}
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTS=OFF \
            -DSYS_OPENSSL=ON \
            -DOPENSSL_USE_STATIC_LIBS=TRUE \
            -DOPENSSL_ROOT_DIR=${{env.open_ssl_path}} \
            -DTARGET_JNI=ON \
            ../${{env.source_path}}
      - 
        name: Build - Make
        run: |
          make -j$(sysctl -n hw.ncpu)
        working-directory: ${{env.build_path}}
      - 
        name: Build - Jar
        run: |
          cp -v ${{env.source_path}}/api/core/java/* .
          cp -v ${{env.source_path}}/api/core/scala/* .
          mkdir -p src/main/resources/resources/djinni_native_libs
          cp  ${{env.build_path}}/core/src/libledger-core.dylib src/main/resources/resources/djinni_native_libs/libledger-core_jni.dylib
          sbt package
          find . -name \*.jar -exec mv {} ${{env.build_path}}/core/src/ledger-lib-core.jar
        working-directory: ${{env.build_jar_path}}
      - 
        name : Upload release build files
        uses: actions/upload-artifact@v2
        with:
          name: macOS_release_build_files
          path: |
            ${{env.build_path}}/core/src/libledger-core-static.a
            ${{env.build_path}}/core/src/libledger-core.dylib
            ${{env.build_path}}/core/src/ledger-lib-core.jar
      - 
        name: Clean workspace
        if: ${{ always() }}
        run: |
          rm -rf "${{github.workspace}}/${{env.build_path}}"
          rm -rf "${{github.workspace}}/${{env.build_jar_path}}"
          
  #########
  # DEBUG #
  #########
  debug:
    needs: prepare
    runs-on: [self-hosted, macos, x64]
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{env.source_path}}
          clean: true
          submodules: true
      -
        name: Build - Cmake
        run: |
          if [ -d "${{env.build_path}}" ]; 
            then rm -Rf ${{env.build_path}}; 
          fi
          mkdir ${{env.build_path}}
          cd ${{env.build_path}}
          cmake \
            -DCMAKE_BUILD_TYPE=Debug \
            -DBUILD_TESTS=ON \
            -DSYS_OPENSSL=ON \
            -DOPENSSL_USE_STATIC_LIBS=TRUE \
            -DOPENSSL_ROOT_DIR=${{env.open_ssl_path}} \
            ../${{env.source_path}}
      - 
        name: Build - Make
        run: |
          make -j$(sysctl -n hw.ncpu)
        working-directory: ${{env.build_path}}
      - 
        name : Upload debug build files
        uses: actions/upload-artifact@v2
        with:
          name: macOS_debug_build_files
          path: |
            ${{env.build_path}}/core/src/libledger-core-static.a
            ${{env.build_path}}/core/src/libledger-core.dylib
      - 
        name: Run Unit Tests
        run: |
          ctest --timeout 180 -VV
        continue-on-error: true
        working-directory: ${{env.build_path}}
      -
        name: Generate coverage
        run: |
          lcov \
            --directory core/src \
            --base-directory ../${{env.source_path}}/core/src \
            --no-external \
            --capture \
            --rc lcov_branch_coverage=1 \
            -o lcov.info
        working-directory: ${{env.build_path}}
      - 
        name: Coverage summary
        run: |
          lcov \
            --summary \
            --rc lcov_branch_coverage=1 \
            lcov.info
        working-directory: ${{env.build_path}}
      - 
        name: Generate coverage report
        run: |
          genhtml --ignore-errors \
            source lcov.info \
            --title "Libcore: Unit Test Coverage (macOS, Debug)" \
            --frames \
            --show-details \
            --keep-descriptions \
            --demangle-cpp \
            --function-coverage \
            --branch-coverage \
            --output-directory=macOS_coverage_report
        working-directory: ${{env.build_path}}
      - 
        name: Compress coverage report
        run: |
          tar -cvzf macOS_coverage_report.tar.gz macOS_coverage_report
        working-directory: ${{env.build_path}}
      - 
        name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: macOS_coverage_report
          path: |
            ${{env.build_path}}/MacOS_coverage_report.tar.gz
      - 
        name: Clean workspace
        if: ${{ always() }}
        run: |
          rm -rf "${{github.workspace}}/${{env.build_path}}"